server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/faxnug/config           # 公用
  application:
    name: configserver
  security:
    user:
      name: user
      password: 123456